# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.inquisitivethinking.com
title: Inquisitive Thinking Ltd
email: eva@inquisitivethinking.com
author: Eva Villarroya
description: > # "E-commerce Hybris consultant. Keep in touch for availability."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/inquisitiveltd
  - title: linkedin
    url: https://www.linkedin.com/in/eva-v-8870698
